name: hello world

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - name: hello world step1
      - run: echo Hi